#!/usr/bin/env python

# Copyright (C) 2014  Open Data ("Open Data" refers to
# one or more of the following companies: Open Data Partners LLC,
# Open Data Research LLC, or Open Data Capital LLC.)
# 
# This file is part of Hadrian.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
import os.path
import re

from titus.inspector.main import InspectorMode
from titus.inspector.jsongadget import JsonGadget
from titus.inspector.pfagadget import PFAGadget

if __name__ == "__main__":
    initialCommands = []
    for fileName in sys.argv[1:]:
        modelName = os.path.split(os.path.expanduser(fileName))[1]
        if modelName.endswith(".pfa") or modelName.endswith(".yml"):
            modelName = modelName[:-4]
        if modelName.endswith(".json") or modelName.endswith(".yaml"):
            modelName = modelName[:-5]
        modelName = re.sub("[^A-Za-z0-9_]", "_", modelName)
        if re.match("^[0-9]", modelName):
            modelName = "m" + modelName

        initialCommands.append("load {0} as {1}".format(fileName, modelName))

    mode = InspectorMode(initialCommands, [JsonGadget, PFAGadget])
    mode.loop()
